# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Stanislav Sidelnikov
subtitle: iOS and Mac OS X Developer
email: stan@stansidel.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about iOS, Mac OS X, web and general software development.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.stansidel.com" # the base hostname & protocol for your site
twitter_username: stansidel
github_username:  stansidel

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:path/

exclude: [vendor, "Gemfile", "Gemfile.lock"]
